name: build
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'corretto'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Gradle Generate Javadoc
        uses: gradle/gradle-build-action@v2
        with:
          arguments: javadoc

      - name: Upload Java JAR
        uses: actions/upload-artifact@v3
        with:
          name: Java JAR
          path: build/libs

      - name: Publish Java Docs
        uses: actions/upload-artifact@v3
        with:
          name: Java Docs
          path: build/docs/javadoc

      - name: Remove .gitignore file
        run: rm -f .gitignore

      - name: Commit Javadoc
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          message: "Update Javadoc by GitHub Actions"
          add: "build/docs/javadoc"
          branch: "gh-pages"